#!/bin/sh

if [ $# -eq 0 ]; then
  echo "You have to pass at least one argument. For more information see the README of the repository."
  exit 1
fi

JAVA_OPTS=\
"-Dhttp.proxyHost=proxy2.keylane.local "\
"-Dhttp.proxyPort=3128 "\
"-Dhttp.nonProxyHosts=*.keylane* "\
"-Dhttps.proxyHost=proxy2.keylane.local "\
"-Dhttps.proxyPort=3128"

CLASSPATH=\
C:/git/advent-of-code/cli/build/classes/kotlin/main\;\
C:/Users/jveenstr/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.8.21/67f57e154437cd9e6e9cf368394b95814836ff88/kotlin-stdlib-jdk8-1.8.21.jar\;\
C:/Users/jveenstr/.gradle/caches/modules-2/files-2.1/com.github.ajalt.clikt/clikt-jvm/3.5.2/c2260b9cd50ee1a2c68936b72235b19e001cf8c1/clikt-jvm-3.5.2.jar\;\
C:/Users/jveenstr/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.8.21/7473b8cd3c0ef9932345baf569bc398e8a717046/kotlin-stdlib-jdk7-1.8.21.jar\;\
C:/Users/jveenstr/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.8.21/43d50ab85bc7587adfe3dda3dbe579e5f8d51265/kotlin-stdlib-1.8.21.jar\;\
C:/Users/jveenstr/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.8.21/d749cd5ae25da36d06e5028785038e24f9d37976/kotlin-stdlib-common-1.8.21.jar\;\
C:/Users/jveenstr/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar

$JAVA_HOME/bin/java $JAVA_OPTS -cp $CLASSPATH CliKt "$@"