[versions]
cliKt = "5.1.0"
junit = "6.1.3"
kotlin = "2.4.20"
kotlinx-collections-immutable = "0.5.2"

[libraries]
cliKt = { module = "com.github.ajalt.clikt:clikt", version.ref = "cliKt" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
